# Generated by Django 3.1.4 on 2020-12-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('points', models.IntegerField()),
                ('rebounds', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('blocks', models.IntegerField()),
                ('steals', models.IntegerField()),
                ('fg_pct', models.FloatField()),
                ('ft_pct', models.FloatField()),
                ('threes', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('turnovers', models.IntegerField()),
                ('positions', models.ManyToManyField(to='assistant.Position')),
                ('rank', models.IntegerField()),
                ('avg_rank', models.FloatField()),
            ],
        ),
    ]
