# Generated by Django 3.1.4 on 2020-12-13 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0002_positions_and_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('overall_number', models.IntegerField()),
                ('owned_by_user', models.BooleanField(default=False)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.player')),
            ],
        ),
    ]
