# Generated by Django 3.1.4 on 2020-12-17 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_auto_20201213_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZScoreSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsZ', models.FloatField()),
                ('reboundsZ', models.FloatField()),
                ('assistsZ', models.FloatField()),
                ('blocksZ', models.FloatField()),
                ('stealsZ', models.FloatField()),
                ('fg_pctZ', models.FloatField()),
                ('ft_pctZ', models.FloatField()),
                ('threesZ', models.FloatField()),
                ('turnoversZ', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.player')),
            ],
        ),
    ]
