# Generated by Django 3.1.4 on 2020-12-17 06:47

from django.db import migrations
from assistant.constants import projection_statistics as ps

def Z(mean, sd, value):
    return (float(value) - mean)/sd

def calculate_all_zscores(apps, schema_editor):
    Player = apps.get_model('assistant','Player')
    allplayers = Player.objects.all()

    ZScoreSet = apps.get_model('assistant','ZScoreSet')
    for player in allplayers:
        ZScoreSet.objects.create(
            player = player,

            pointsZ = Z(ps['points_m'], ps['points_sd'], player.points),
            reboundsZ = Z(ps['rebounds_m'], ps['rebounds_sd'], player.rebounds),
            assistsZ = Z(ps['assists_m'], ps['assists_sd'], player.assists),
            blocksZ = Z(ps['blocks_m'], ps['blocks_sd'], player.blocks),
            stealsZ = Z(ps['steals_m'], ps['steals_sd'], player.steals),
            fg_pctZ = Z(ps['fg_pct_m'], ps['fg_pct_sd'], player.fg_pct),
            ft_pctZ = Z(ps['ft_pct_m'], ps['ft_pct_sd'], player.ft_pct),
            threesZ = Z(ps['threes_m'], ps['threes_sd'], player.threes),
            turnoversZ = Z(ps['turnovers_m'], ps['turnovers_sd'], player.turnovers),
        )
        print(f'zscores calculated for {player.name}')



class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_zscoreset'),
    ]

    operations = [
        migrations.RunPython(calculate_all_zscores)
    ]
