# Generated by Django 3.1.4 on 2020-12-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_calculate_all_zscores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='user',
            new_name='commissioner',
        ),
        migrations.RenameField(
            model_name='draftpick',
            old_name='overall_number',
            new_name='overall_place',
        ),
        migrations.RenameField(
            model_name='draftpick',
            old_name='round_number',
            new_name='round_picked',
        ),
        migrations.RemoveField(
            model_name='draftpick',
            name='owned_by_user',
        ),
        migrations.AddField(
            model_name='draftpick',
            name='round_place',
            field=models.IntegerField(null=True),
        ),
    ]
