# Generated by Django 3.1.4 on 2020-12-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_draftpick_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='commissioner',
            new_name='creator',
        ),
    ]
